language: android

android:
  components:
  	- tools
    - build-tools-21.1.2
    - android-22
    - extra-android-support
    - extra-android-m2repository

jdk: oraclejdk8

script:
 - ./gradlew clean build  --stacktrace

after_success:
 - ./gradlew

notifications:
  email: change