language: android
jdk: oraclejdk8

android:
  components:
  - android-22
  - build-tools-21.1.2

script:
 - ./gradlew clean build  --stacktrace

after_success:
 - ./gradlew

notifications:
  email: change