language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.2
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
 - ./gradlew clean build  --stacktrace

after_success:
 - ./gradlew

notifications:
  email: change